# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]

#standalone tags for the maze
#6 standalone tags for the cube (992 - 997)
standalone_tags:
  [
    {id: 72, size: 0.084, name: tag_72},
    {id: 73, size: 0.0168, name: tag_72},
    {id: 84, size: 0.084, name: tag_84},
    {id: 85, size: 0.0168, name: tag_85},
    {id: 80, size: 0.084, name: tag_80},
    {id: 81, size: 0.0168, name: tag_81},
    {id: 2, size: 0.084, name: tag_2},
    {id: 3, size: 0.0168, name: tag_3},
    {id: 20, size: 0.084, name: tag_20},
    {id: 21, size: 0.0168, name: tag_21},
    {id: 32, size: 0.084, name: tag_32},
    {id: 33, size: 0.0168, name: tag_33},
    {id: 38, size: 0.084, name: tag_38},
    {id: 39, size: 0.0168, name: tag_39},
    {id: 34, size: 0.084, name: tag_34},
    {id: 35, size: 0.0168, name: tag_35},
    {id: 36, size: 0.084, name: tag_36},
    {id: 37, size: 0.0168, name: tag_37},
    {id: 28, size: 0.084, name: tag_28},
    {id: 29, size: 0.0168, name: tag_29},
    {id: 42, size: 0.084, name: tag_42},
    {id: 43, size: 0.0168, name: tag_43},
    {id: 30, size: 0.084, name: tag_30},
    {id: 31, size: 0.0168, name: tag_31},
    {id: 40, size: 0.084, name: tag_40},
    {id: 41, size: 0.0168, name: tag_41},
    {id: 26, size: 0.084, name: tag_26},
    {id: 27, size: 0.0168, name: tag_27},
    {id: 44, size: 0.084, name: tag_44},
    {id: 45, size: 0.0168, name: tag_45},
    {id: 60, size: 0.084, name: tag_60},
    {id: 61, size: 0.0168, name: tag_61},
    {id: 88, size: 0.084, name: tag_88},
    {id: 89, size: 0.0168, name: tag_89},
    {id: 48, size: 0.084, name: tag_48},
    {id: 49, size: 0.0168, name: tag_49},
    {id: 56, size: 0.084, name: tag_56},
    {id: 57, size: 0.0168, name: tag_57},
    {id: 0, size: 0.084, name: tag_0},
    {id: 1, size: 0.0168, name: tag_1},
    {id: 22, size: 0.084, name: tag_22},
    {id: 23, size: 0.0168, name: tag_23},
    {id: 8, size: 0.084, name: tag_8},
    {id: 9, size: 0.0168, name: tag_9},
    {id: 14, size: 0.084, name: tag_14},
    {id: 15, size: 0.0168, name: tag_15},
    {id: 68, size: 0.084, name: tag_68},
    {id: 69, size: 0.0168, name: tag_69},
    {id: 64, size: 0.084, name: tag_64},
    {id: 65, size: 0.0168, name: tag_65},
    {id: 4, size: 0.084, name: tag_4},
    {id: 5, size: 0.0168, name: tag_5},
    {id: 18, size: 0.084, name: tag_18},
    {id: 19, size: 0.0168, name: tag_19},
    {id: 10, size: 0.084, name: tag_10},
    {id: 11, size: 0.0168, name: tag_11},
    {id: 12, size: 0.084, name: tag_12},
    {id: 13, size: 0.0168, name: tag_13},
    {id: 92, size: 0.084, name: tag_92},
    {id: 93, size: 0.0168, name: tag_93},
    {id: 76, size: 0.084, name: tag_76},
    {id: 77, size: 0.0168, name: tag_77},
    {id: 6, size: 0.084, name: tag_6},
    {id: 7, size: 0.0168, name: tag_7},
    {id: 16, size: 0.084, name: tag_16},
    {id: 17, size: 0.0168, name: tag_17},
    {id: 24, size: 0.084, name: tag_24},
    {id: 25, size: 0.0168, name: tag_25},
    {id: 46, size: 0.084, name: tag_46},
    {id: 47, size: 0.0168, name: tag_47},
    {id: 52, size: 0.084, name: tag_52},
    {id: 53, size: 0.0168, name: tag_53},
    {id: 110, size: 0.084, name: tag_110},
    {id: 109, size: 0.0168, name: tag_109},
    {id: 992, size: 0.0162},
    {id: 993, size: 0.0162}, 
    {id: 994, size: 0.0162}, 
    {id: 995, size: 0.0162}, 
    {id: 996, size: 0.0162}, 
    {id: 997, size: 0.0162} 
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [ 
    {
      name: 'world',
      layout:
        [
          {id: 72, size: 0.084, x: 0.003, y: 0.128, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 73, size: 0.0168, x: 0.003, y: 0.128, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 84, size: 0.084, x: 0.003, y: 0.381, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 85, size: 0.0168, x: 0.003, y: 0.381, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 80, size: 0.084, x: 0.003, y: 0.634, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 81, size: 0.0168, x: 0.003, y: 0.634, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 2, size: 0.084, x: 0.253, y: 0.128, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 3, size: 0.0168, x: 0.253, y: 0.128, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 20, size: 0.084, x: 0.256, y: 0.128, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 21, size: 0.0168, x: 0.256, y: 0.128, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 32, size: 0.084, x: 0.253, y: 0.381, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 33, size: 0.0168, x: 0.253, y: 0.381, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 38, size: 0.084, x: 0.256, y: 0.381, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 39, size: 0.0168, x: 0.256, y: 0.381, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 34, size: 0.084, x: 0.253, y: 0.634, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 35, size: 0.0168, x: 0.253, y: 0.634, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 36, size: 0.084, x: 0.256, y: 0.634, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 37, size: 0.0168, x: 0.256, y: 0.634, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 28, size: 0.084, x: 0.506, y: 0.128, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 29, size: 0.0168, x: 0.506, y: 0.128, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 42, size: 0.084, x: 0.509, y: 0.128, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 43, size: 0.0168, x: 0.509, y: 0.128, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 30, size: 0.084, x: 0.506, y: 0.381, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 31, size: 0.0168, x: 0.506, y: 0.381, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 40, size: 0.084, x: 0.509, y: 0.381, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 41, size: 0.0168, x: 0.509, y: 0.381, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 26, size: 0.084, x: 0.506, y: 0.634, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 27, size: 0.0168, x: 0.506, y: 0.634, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 44, size: 0.084, x: 0.509, y: 0.634, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 45, size: 0.0168, x: 0.509, y: 0.634, z: 0.088, qw: 0.5, qx: 0.5, qy: 0.5, qz: 0.5},
          {id: 60, size: 0.084, x: 0.759, y: 0.128, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 61, size: 0.0168, x: 0.759, y: 0.128, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 88, size: 0.084, x: 0.759, y: 0.381, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 89, size: 0.0168, x: 0.759, y: 0.381, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 48, size: 0.084, x: 0.759, y: 0.634, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 49, size: 0.0168, x: 0.759, y: 0.634, z: 0.088, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 56, size: 0.084, x: 0.128, y: 0.003, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 57, size: 0.0168, x: 0.128, y: 0.003, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 0, size: 0.084, x: 0.128, y: 0.253, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 1, size: 0.0168, x: 0.128, y: 0.253, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 22, size: 0.084, x: 0.128, y: 0.256, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 23, size: 0.0168, x: 0.128, y: 0.256, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 8, size: 0.084, x: 0.128, y: 0.506, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 9, size: 0.0168, x: 0.128, y: 0.506, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 14, size: 0.084, x: 0.128, y: 0.509, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 15, size: 0.0168, x: 0.128, y: 0.509, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 68, size: 0.084, x: 0.128, y: 0.759, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 69, size: 0.0168, x: 0.128, y: 0.759, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 64, size: 0.084, x: 0.381, y: 0.003, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 65, size: 0.0168, x: 0.381, y: 0.003, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 4, size: 0.084, x: 0.381, y: 0.253, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 5, size: 0.0168, x: 0.381, y: 0.253, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 18, size: 0.084, x: 0.381, y: 0.256, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 19, size: 0.0168, x: 0.381, y: 0.256, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 10, size: 0.084, x: 0.381, y: 0.506, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 11, size: 0.0168, x: 0.381, y: 0.506, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 12, size: 0.084, x: 0.381, y: 0.509, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 13, size: 0.0168, x: 0.381, y: 0.509, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 92, size: 0.084, x: 0.381, y: 0.759, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 93, size: 0.0168, x: 0.381, y: 0.759, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 76, size: 0.084, x: 0.634, y: 0.003, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 77, size: 0.0168, x: 0.634, y: 0.003, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 6, size: 0.084, x: 0.634, y: 0.253, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 7, size: 0.0168, x: 0.634, y: 0.253, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 16, size: 0.084, x: 0.634, y: 0.256, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 17, size: 0.0168, x: 0.634, y: 0.256, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 24, size: 0.084, x: 0.634, y: 0.506, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 25, size: 0.0168, x: 0.634, y: 0.506, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 46, size: 0.084, x: 0.634, y: 0.509, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 47, size: 0.0168, x: 0.634, y: 0.509, z: 0.088, qw: 0, qx: 0, qy: 0.7071068, qz: 0.7071068},
          {id: 52, size: 0.084, x: 0.634, y: 0.759, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 53, size: 0.0168, x: 0.634, y: 0.759, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 110, size: 0.084, x: 0.634, y: 0.759, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0},
          {id: 109, size: 0.0168, x: 0.634, y: 0.759, z: 0.088, qw: 0.7071068, qx: 0.7071068, qy: 0, qz: 0}
        ]
    }
  ]
